-- 코드를 입력하세요
SELECT PD.APNT_NO, P.PT_NAME, PD.PT_NO, PD.MCDP_CD, D.DR_NAME, PD.APNT_YMD
    FROM APPOINTMENT PD
        INNER JOIN PATIENT P ON PD.PT_NO = P.PT_NO
        INNER JOIN DOCTOR D ON PD.MDDR_ID = D.DR_ID
    WHERE APNT_YMD Like '2022-04-13%' 
        AND PD.APNT_CNCL_YN = 'N' 
        AND PD.MCDP_CD = 'CS'
    ORDER BY APNT_YMD ASC
